---
title: "LDA"
author: "Changhao Ge"
date: "3/24/2021"
output: html_document
---
Parameter estimation:
```{r}
library('DIRECT')
#some settings and initial conditions
D=30            #documents number
N=100           #words number per document(set the same w.l.g)
K=10            #total topic number
V=100           #size of alphabet
niter=100       #number of outer iteration
niniter=10      #number of inner iteration
w=array(0,dim=c(D,N,V))
phi=array(1/K,dim=c(D,N,K))
bet=matrix(sample(1:3,K*V,replace=T),K,V)
for(i in 1:K){
  bet[i,]=bet[i,]/sum(bet[i,])
 # bet[i,10*(i-1)+1:10]=0.1
}
gamm=array(0,dim=c(D,K))
alph=sample(2:4,K,replace=T)
set.seed(10)
doctop=array(0,dim=c(D,3))
for(d in 1:D){
  gamm[d,]=alph+N/K
  doctop[d,]=sample(1:K,3)
  for(n in 1:N){
    a=sample(1:3,1)
    b=sample(10*(doctop[d,a]-1)+1:10,1)
    w[d,n,b]=1
  }
}

# begin parameter estimation
#E-step
for(iter in 1:niter){
  for(d in 1:D){
    for(n in 1:N){
      for(i in 1:K){
        phi[d,n,i]=bet[i,which(w[d,n,]==1)]*exp(digamma(gamm[d,i]))
      }
      phi[d,n,]=phi[d,n,]/sum(phi[d,n,])
    }
    gamm[d,]=alph+colSums(phi[d,,])
  }
  #M-step
  for(i in 1:K){
    for(j in 1:V){
      bet[i,j]=0
      for(d in 1:D){
        for(n in 1:N){
          bet[i,j]=bet[i,j]+phi[d,n,i]*w[d,n,j]
        }
      }
    }
    bet[i,]=bet[i,]/sum(bet[i,])
  }
  temp=rep(0,K)
  L=rep(0,K)
  for(d in 1:D) temp=temp+digamma(gamm[d,])-digamma(sum(gamm[d,]))
  for(initer in 1:niniter){
  L=D*(digamma(sum(alph))-digamma(alph))+temp
  h=-D*trigamma(alph)
  z=D*trigamma(sum(alph))
  c=sum(L/h)/(z^(-1)+sum(h^(-1)))
  alph=alph-0.5*(L-c)/h
  }
}
plot(1:V,bet[1,],lty=1)
for(i in 1:K){
  print(paste('The',i,'th row of beta with probability larger than 4e-2:'))
  print(which(bet[i,]>4e-2))
}
```

Inference:
```{r}
phi_new=matrix(1/K,N,K)
w_new=matrix(0,N,V)
for(i in 1:N){
  a=sample(c(1,3,7),1)           #set the topic of new document as 1,3,7
  w_new[i,sample(10*(a-1)+1:10,1)]=1
}
gamm_new=alph+N/K
for(iter in 1:niter){
    for(n in 1:N){
      for(i in 1:K){
        phi_new[n,i]=bet[i,which(w_new[n,]==1)]*exp(digamma(gamm_new[i]))
      }
      phi_new[n,]=phi_new[n,]/sum(phi_new[n,])
    }
    gamm_new=alph+colSums(phi_new)
}
Tem=numeric(N)
for(i in 1:N) Tem[i]=which(phi_new[i,]>0.8)
unique(Tem)
```